import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Smile tree dental',
  description: 'Generated by Design Factory',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
